version: "3.8"
services:
  roomba_navigation:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        progress: plain
    network_mode: host
    restart: always
    privileged: true
    container_name: roomba_navigation
    platform: linux/arm64
    tty: true
    volumes:
      - /dev:/dev
      - /home/ubuntu/Projects/robot-i-ros2/src/roomba_bringup:/usr/src/ros2_ws/src/roomba_bringup
      - /home/ubuntu/Projects/robot-i-ros2/src/roomba_navigation:/usr/src/ros2_ws/src/roomba_navigation
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
