version: "3.8"
services:
  roomba_navigation:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        progress: plain
    network_mode: host
    restart: always
    privileged: true
    container_name: roomba_navigation

  roomba_bridge:
    image: ros12bridge-roomba_bridge
    network_mode: host
    restart: always
    privileged: true

  roomba_noetic:
    image: robot-i-ros1-roomba_noetic
    network_mode: host
    restart: always
    privileged: true
    volumes:
      -
        /dev:/dev